name: Deploy Blog

on: 
  push:
    branches: dev # dev 브랜치에 push가 발생하면 workflow 실행

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: node-version: 20

      - name: Generate env file
        run: |
          echo "CONTENTFUL_ACCESS_TOKEN=$CONTENTFUL_ACCESS_TOKEN" >> .env
          echo "CONTENTFUL_SPACE_ID=$CONTENTFUL_SPACE_ID" >> .env
        env:
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}

      - name: Deploy gatsby
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
          deploy-branch: main  # main 브랜치에 빌드 파일을 푸쉬하도록 설정
          gatsby-args: --verbose  # 빌드 과정 출력